from abc import ABC, abstractmethod


class ParkingRepository(ABC):
    @abstractmethod
    def crear_cliente(self, cliente): ...

    @abstractmethod
    def obtener_cliente(self, cliente_id): ...

    @abstractmethod
    def crear_usuario(self, usuario): ...

    @abstractmethod
    def obtener_usuario(self, usuario_id): ...

    @abstractmethod
    def crear_vehiculo(self, vehiculo): ...

    @abstractmethod
    def obtener_vehiculo(self, vehiculo_id): ...

    @abstractmethod
    def crear_plaza(self, plaza): ...

    @abstractmethod
    def obtener_plaza(self, plaza_id): ...

    @abstractmethod
    def listar_plazas(self): ...

    @abstractmethod
    def actualizar_plaza(self, plaza): ...

    @abstractmethod
    def eliminar_plaza(self, plaza_id): ...

    @abstractmethod
    def obtener_estancia_activa_vehiculo(self, vehiculo_id): ...

    @abstractmethod
    def obtener_estancia_activa_plaza(self, plaza_id): ...

    @abstractmethod
    def obtener_estancia_activa(self, estancia_id): ...

    @abstractmethod
    def crear_estancia(self, estancia): ...

    @abstractmethod
    def cerrar_estancia(self, estancia_id, salida): ...

    @abstractmethod
    def listar_estancias_activas(self): ...